// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
pub mod org {
  use super::*;
  pub mod apache {
    use super::*;
    pub mod arrow {
      use super::*;
      pub mod flatbuf {
        use super::*;
        mod metadata_version;
        pub use self::metadata_version::*;
        mod feature;
        pub use self::feature::*;
        mod union_mode;
        pub use self::union_mode::*;
        mod precision;
        pub use self::precision::*;
        mod date_unit;
        pub use self::date_unit::*;
        mod time_unit;
        pub use self::time_unit::*;
        mod interval_unit;
        pub use self::interval_unit::*;
        mod type;
        pub use self::type::*;
        mod dictionary_kind;
        pub use self::dictionary_kind::*;
        mod endianness;
        pub use self::endianness::*;
        mod null;
        pub use self::null::*;
        mod struct_;
        pub use self::struct_::*;
        mod list;
        pub use self::list::*;
        mod large_list;
        pub use self::large_list::*;
        mod list_view;
        pub use self::list_view::*;
        mod large_list_view;
        pub use self::large_list_view::*;
        mod fixed_size_list;
        pub use self::fixed_size_list::*;
        mod map;
        pub use self::map::*;
        mod union;
        pub use self::union::*;
        mod int;
        pub use self::int::*;
        mod floating_point;
        pub use self::floating_point::*;
        mod utf_8;
        pub use self::utf_8::*;
        mod binary;
        pub use self::binary::*;
        mod large_utf_8;
        pub use self::large_utf_8::*;
        mod large_binary;
        pub use self::large_binary::*;
        mod utf_8_view;
        pub use self::utf_8_view::*;
        mod binary_view;
        pub use self::binary_view::*;
        mod fixed_size_binary;
        pub use self::fixed_size_binary::*;
        mod bool;
        pub use self::bool::*;
        mod run_end_encoded;
        pub use self::run_end_encoded::*;
        mod decimal;
        pub use self::decimal::*;
        mod date;
        pub use self::date::*;
        mod time;
        pub use self::time::*;
        mod timestamp;
        pub use self::timestamp::*;
        mod interval;
        pub use self::interval::*;
        mod duration;
        pub use self::duration::*;
        mod key_value;
        pub use self::key_value::*;
        mod dictionary_encoding;
        pub use self::dictionary_encoding::*;
        mod field;
        pub use self::field::*;
        mod buffer;
        pub use self::buffer::*;
        mod schema;
        pub use self::schema::*;
        mod tensor_dim;
        pub use self::tensor_dim::*;
        mod tensor;
        pub use self::tensor::*;
      } // flatbuf
    } // arrow
  } // apache
} // org
