[package]
name = "parquet_redux"
version.workspace = true
edition.workspace = true

[dependencies]
rayexec_error = { path = "../rayexec_error" }
rayexec_bullet = { path = "../rayexec_bullet" }
thrift = { version = "0.17", default-features = false }
num = { workspace = true }
