name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
          submodules: 'true'

      - name: Tests
        run: cargo test -- --skip slt_datasource_

      - name: SLTs Postgres
        run: |
          ./scripts/create-test-postgres-db.sh
          cargo test slt_datasource_postgres

      - name: Lint
        run: cargo clippy --all --all-features -- --deny warnings

  wasm:
    name: "Build and publish WASM"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      # - name: Build and publish
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: |
      #     echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      #     wasm-pack build crates/rayexec_wasm/ --scope glaredb
      #     wasm-pack publish crates/rayexec_wasm/
